CREATE TABLE IF NOT EXISTS ratings
(
  id BIGSERIAL NOT NULL,
  userId BIGSERIAL NOT NULL,
  rating INTEGER,
  category CHARACTER VARYING(64) NOT NULL,
  categoryItem CHARACTER VARYING(64) NOT NULL,
  comment CHARACTER VARYING(1024),
  userRole CHARACTER VARYING(64),
  CONSTRAINT ratings_pkey PRIMARY KEY (id)
);