ALTER TABLE oskari_appsetup ALTER COLUMN created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE oskari_appsetup ALTER COLUMN used TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE oskari_appsetup ADD "updated" TIMESTAMP WITH TIME ZONE;