DROP TABLE portti_inspiretheme IF EXISTS;
DROP TABLE portti_layerclass IF EXISTS;
DROP TABLE portti_maplayer IF EXISTS;
DROP TABLE portti_permissions IF EXISTS;
DROP TABLE portti_resource_user IF EXISTS;
DROP TABLE  portti_maplayer_metadata IF EXISTS;
DROP TABLE  portti_capabilities_cache IF EXISTS;

DROP VIEW portti_backendalert IF EXISTS;
DROP VIEW  portti_backendstatus_allknown IF EXISTS;
DROP TABLE  portti_backendstatus IF EXISTS;

CREATE TABLE portti_capabilities_cache
(
  layer_id IDENTITY,
  data character varying(20000),
  updated timestamp DEFAULT CURRENT_TIMESTAMP,
  "WMSversion" character(10) NOT NULL,
  CONSTRAINT portti_capabilities_cache_pkey PRIMARY KEY (layer_id)
);

CREATE TABLE portti_inspiretheme (
  id IDENTITY,
  locale character varying(20000),
  CONSTRAINT portti_inspiretheme_pkey PRIMARY KEY (id)
);


CREATE TABLE portti_layerclass (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  namefi character varying(2000),
  namesv character varying(2000),
  nameen character varying(2000),
  maplayers_selectable boolean DEFAULT false,
  parent integer DEFAULT null,
  legend_image character varying(2000) DEFAULT '',
  dataurl character varying(2000) DEFAULT '',
  group_map boolean DEFAULT false,
  locale character varying(20000),
  CONSTRAINT portti_layerclass_pkey PRIMARY KEY (id)

);


CREATE TABLE portti_maplayer (
  id IDENTITY,
  layerclassid integer,
  namefi character varying(2000) default '',
  namesv character varying(2000) default '',
  nameen character varying(2000) default '',
  wmsname character varying(2000) default '',
  wmsurl character varying(2000) default '',
  opacity integer default 100,
  style character varying(20000) default '',
  minscale double precision default 0,
  maxscale double precision default 0,
  description_link character varying(2000) default '',
  legend_image character varying(2000) default '',
  inspire_theme_id integer default 0,
  dataurl character varying(2000) default '',
  metadataurl character varying(2000) default '',
  order_number integer default 0,
  layer_type character varying(100) NOT NULL,
  tile_matrix_set_id character varying(1024) default '',
  tile_matrix_set_data character varying(20000) default '',
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  updated timestamp DEFAULT CURRENT_TIMESTAMP,
  wms_dcp_http character varying(2000) default '',
  wms_parameter_layers character varying(2000) default '',
  resource_url_scheme character varying(100) default '',
  resource_url_scheme_pattern character varying(2000) default '',
  resource_url_client_pattern character varying(2000) default '',
  resource_daily_max_per_ip integer default -1,
  xslt character varying(20000) default '',
  gfi_type character varying(2000) default '',
  subtitle_fi character varying(2000) default '',
  subtitle_en character varying(2000) default '',
  subtitle_sv character varying(2000) default '',
  selection_style character varying(20000) default '',
  "VERSION" character varying(10) default '',
  epsg integer DEFAULT 3067,
  locale character varying(20000),
  CONSTRAINT portti_maplayer_pkey PRIMARY KEY (id)

);



CREATE TABLE portti_permissions (
  id IDENTITY,
  resource_user_id integer NOT NULL,
  permissions_type character varying(100),
  CONSTRAINT portti_permissions_pkey PRIMARY KEY (id)
);


CREATE TABLE portti_resource_user (
  id IDENTITY,
  resource_name character varying(1000),
  resource_namespace character varying(1000),
  resource_type character varying(100),
  externalid character varying(1000),
  externalid_type character varying(20),
  CONSTRAINT portti_resource_user_pkey PRIMARY KEY (id)

);

CREATE TABLE portti_maplayer_metadata
(
  id IDENTITY NOT NULL,
  maplayerid integer,
  uuid character varying(256),
  namefi character varying(512),
  namesv character varying(512),
  nameen character varying(512),
  abstractfi character varying(1024),
  abstractsv character varying(1024),
  abstracten character varying(1024),
  browsegraphic character varying(1024),
  geom character varying(512) default '',
  CONSTRAINT portti_maplayer_metadata_pkey PRIMARY KEY (id)
);


 CREATE TABLE portti_backendstatus
 (
   id IDENTITY,
   ts timestamp DEFAULT CURRENT_TIMESTAMP,
   maplayer_id character varying(50),
   status character varying(500),
   statusmessage character varying(2000),
   infourl character varying(2000),
   statusjson character varying(20000),
   CONSTRAINT portti_backendstatus_pkey PRIMARY KEY (id)
 );

CREATE VIEW portti_backendalert as SELECT id,ts,maplayer_id,status,statusmessage,infourl,statusjson FROM portti_backendstatus WHERE NOT status is null AND NOT status = 'UNKNOWN' AND NOT status = 'OK';

CREATE VIEW portti_backendstatus_allknown AS
 SELECT portti_backendstatus.id, portti_backendstatus.ts, portti_backendstatus.maplayer_id, portti_backendstatus.status, portti_backendstatus.statusmessage, portti_backendstatus.infourl, portti_backendstatus.statusjson
   FROM portti_backendstatus;

-- Layer Class;
INSERT INTO portti_layerclass (namefi, namesv, nameen, maplayers_selectable, group_map, locale) values ('Taustakartat','Bakgrundskartor','Background Maps',false, false, '{ fi:{name:"Taustakartat"},sv:{name:"Bakgrundskartor"},en:{name:"Background Maps"}}');
INSERT INTO portti_layerclass (namefi, namesv, nameen, maplayers_selectable, group_map, locale, parent) values ('Taustakartat','Bakgrundskartor','Background Maps',false, false, '{ fi:{name:"Taustakartat"},sv:{name:"Bakgrundskartor"},en:{name:"Background Maps"}}',1);
INSERT INTO portti_layerclass (namefi, namesv, nameen, maplayers_selectable, group_map, locale) values ('Maanmittauslaitos','Lantmäteriverket','National Land Survey',true, false, '{ fi:{name:"Maanmittauslaitos"},sv:{name:"Lantmäteriverket"},en:{name:"National Land Survey"}}');

-- Map Layers;

INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:4milj','Bakgrundskarta 1:4milj','Background map 1:4mill','taustakartta_4m','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',2834657,1417333,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:4milj",subtitle:""},sv:{name:"Bakgrundskarta 1:4milj",subtitle:""},en:{name:"Background map 1:4mill",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:5000','Bakgrundskarta 1:5000','Background map 1:5000','taustakartta_5k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',5000,1,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:5000",subtitle:""},sv:{name:"Bakgrundskarta 1:5000",subtitle:""},en:{name:"Background map 1:5000",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:8milj','Bakgrundskarta 1:8milj','Background map 1:8milj','taustakartta_8m','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',15000000,2834657,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:8milj",subtitle:""},sv:{name:"Bakgrundskarta 1:8milj",subtitle:""},en:{name:"Background map 1:8mill",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:20k','Bakgrundskarta 1:20k','Background map 1:20k','taustakartta_20k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',40001,25001,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:20k",subtitle:""},sv:{name:"Bakgrundskarta 1:20k",subtitle:""},en:{name:"Background map 1:20k",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:800k','Bakgrundskarta 1:800k','Background map 1:800k','taustakartta_800k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',566939,283474,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:800k",subtitle:""},sv:{name:"Bakgrundskarta 1:800k",subtitle:""},en:{name:"Background map 1:800k",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:2milj','Bakgrundskarta 1:2milj','Background map 1:2milj','taustakartta_2m','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',1417333,566939,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:2milj",subtitle:""},sv:{name:"Bakgrundskarta 1:2milj",subtitle:""},en:{name:"Background map 1:2mill",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:320k','Bakgrundskarta 1:320k','Background map 1:320k','taustakartta_320k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',283474,141742,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:320k",subtitle:""},sv:{name:"Bakgrundskarta 1:320k",subtitle:""},en:{name:"Background map 1:320k",subtitle:""}}');

INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:160k','Bakgrundskarta 1:160k','Background map 1:160k','taustakartta_160k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',141742,56702,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:160k",subtitle:""},sv:{name:"Bakgrundskarta 1:160k",subtitle:""},en:{name:"Background map 1:160k",subtitle:""}}');

INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:10k','Bakgrundskarta 1:10k','Background map 1:10k','taustakartta_10k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',25001,5001,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:10k",subtitle:""},sv:{name:"Bakgrundskarta 1:10k",subtitle:""},en:{name:"Background map 1:10k",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:80k','Bakgrundskarta 1:80k','Background map 1:80k','taustakartta_80k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',56702,40000,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:80k",subtitle:""},sv:{name:"Bakgrundskarta 1:80k",subtitle:""},en:{name:"Background map 1:80k",subtitle:""}}');


INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id, 
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (2,'Taustakartta 1:40k','Bakgrundskarta 1:40k','Background map 1:40k','taustakartta_40k','http://a.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://b.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://c.karttatiili.fi/dataset/taustakarttasarja/service/wms,http://d.karttatiili.fi/dataset/taustakarttasarja/service/wms',100,'',2,1,'','',0,'c22da116-5095-4878-bb04-dd7db3a1a341','',2,'wmslayer',
'{ fi:{name:"Taustakartta 1:40k",subtitle:""},sv:{name:"Bakgrundskarta 1:40k",subtitle:""},en:{name:"Background map 1:40k",subtitle:""}}');
   

INSERT INTO portti_maplayer (layerclassid, namefi, namesv, nameen, wmsname, wmsurl, opacity,
       style, minscale, maxscale, description_link, legend_image, inspire_theme_id,
       dataurl, metadataurl, order_number, layer_type, locale)
VALUES (3,'Peruskartta 1:20k','Grundkarta 1:20k','Topographic map 1:20k','peruskartta','http://a.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://b.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://c.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://d.karttatiili.fi/dataset/peruskarttarasteri/service/wms',70,'',25000,1,'','',2,'c22da116-5095-4878-bb04-dd7db3a1a341','',30,'wmslayer',
'{ fi:{name:"Taustakartta 1:20k",subtitle:""},sv:{name:"Bakgrundskarta 1:20k",subtitle:""},en:{name:"Background map 1:20k",subtitle:""}}');


-- permissions;
-- adding permissions to roles with id 10110, 2, and 3;
INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (2, '', 'WMS_LAYER_GROUP', 10110, 'ROLE');
INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (2, '', 'WMS_LAYER_GROUP', 2, 'ROLE');
INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (2, '', 'WMS_LAYER_GROUP', 3, 'ROLE');

INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (3, '', 'WMS_LAYER_GROUP', 10110, 'ROLE');
INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (3, '', 'WMS_LAYER_GROUP', 3, 'ROLE');
INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values (3, '', 'WMS_LAYER_GROUP', 2, 'ROLE');

INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values
('peruskartta', 'http://a.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://b.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://c.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://d.karttatiili.fi/dataset/peruskarttarasteri/service/wms', 'WMS_LAYER', 2, 'ROLE');

INSERT INTO portti_resource_user (resource_name, resource_namespace, resource_type, externalid, externalid_type) values
('peruskartta', 'http://a.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://b.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://c.karttatiili.fi/dataset/peruskarttarasteri/service/wms,http://d.karttatiili.fi/dataset/peruskarttarasteri/service/wms', 'WMS_LAYER', 3, 'ROLE');

INSERT INTO portti_permissions (resource_user_id, permissions_type) values (0, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (1, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (2, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (3, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (4, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (5, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (6, 'VIEW_LAYER');
INSERT INTO portti_permissions (resource_user_id, permissions_type) values (7, 'VIEW_LAYER');


INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Koordinaattijärjestelmät"}, "sv": { "name" : "Referenskoordinatsystem"},"en": { "name" : "Coordinate reference systems"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Paikannusruudustot"}, "sv": { "name" : "Geografiska rutnätssystem"},"en": { "name" : "Geographical grid systems"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Maastokartat"}, "sv": { "name" : "Terrängkartor"},"en": { "name" : "Topographic maps"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Paikannimet"}, "sv": { "name" : "Geografiska namn"},"en": { "name" : "Geographical names"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Hallinnolliset yksiköt"}, "sv": { "name" : "Administrativa enheter"},"en": { "name" : "Administrative units"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Osoitteet"}, "sv": { "name" : "Adresser"},"en": { "name" : "Addresses"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Kiinteistöt"}, "sv": { "name" : "Fastigheter"},"en": { "name" : "Cadastral parcels"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Liikenneverkot"}, "sv": { "name" : "Trafiknät"},"en": { "name" : "Transport networks"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Hydrografia"}, "sv": { "name" : "Hydrografi"},"en": { "name" : "Hydrography"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Suojellut alueet"}, "sv": { "name" : "Skyddade områden"},"en": { "name" : "Protected sites"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Korkeus"}, "sv": { "name" : "Höjd"},"en": { "name" : "Elevation"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Maanpeite"}, "sv": { "name" : "Landtäcke"},"en": { "name" : "Land cover"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Ortoilmakuvat"}, "sv": { "name" : "Ortofoto"},"en": { "name" : "Orthoimagery"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Geologia"}, "sv": { "name" : "Geologi"},"en": { "name" : "Geology"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Korkeus"}, "sv": { "name" : "Höjd"},"en": { "name" : "Elevation"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Tilastoyksiköt"}, "sv": { "name" : "Statistiska enheter"},"en": { "name" : "Statistical units"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Rakennukset"}, "sv": { "name" : "Byggnader"},"en": { "name" : "Buildings"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Maaperä"}, "sv": { "name" : "Mark"},"en": { "name" : "Soil"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Maankäyttö"}, "sv": { "name" : "Markanvändning"},"en": { "name" : "Land use"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Väestön terveys ja turvallisuus"}, "sv": { "name" : "Människors hälsa och säkerhet"},"en": { "name" : "Human health and safety"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Yleishyödylliset ja muut julkiset palvelut"}, "sv": { "name" : "Allmännyttiga och offentliga tjänster"},"en": { "name" : "Utility and governmental services"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Ympäristön tilan seurantalaitteet"}, "sv": { "name" : "Nätverk och anläggningar för miljöövervakning"},"en": { "name" : "Environmental monitoring facilities"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Tuotanto- ja teollisuuslaitokset"}, "sv": { "name" : "Produktions- och industrianläggningar"},"en": { "name" : "Production and industrial facilities"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Maatalous- ja vesiviljelylaitokset"}, "sv": { "name" : "Jordbruks- och vattenbruksanläggningar"},"en": { "name" : "Agricultural and aquaculture facilities"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Väestöjakauma – demografia"}, "sv": { "name" : "Befolkningsfördelning"},"en": { "name" : "Population distribution - demography"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Aluesuunnittelu ja rajoitukset"}, "sv": { "name" : "Områden med särskild reglering"},"en": { "name" : "Area management/restriction zones"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Luonnonriskialueet"}, "sv": { "name" : "Naturliga riskområden"},"en": { "name" : "Natural risk zones"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Ilmakehän tila"}, "sv": { "name" : "Atmosfäriska förhållanden"},"en": { "name" : "Atmospheric conditions"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Ilmaston maantieteelliset ominaispiirteet"}, "sv": { "name" : "Geografiska meteorologiska förhållanden"},"en": { "name" : "Meteorological geographical features"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Merentutkimuksen maantieteelliset ominaispiirteet"}, "sv": { "name" : "Geografiska oceanografiska förhållanden"},"en": { "name" : "Oceanographic geographical features"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Merialueet"}, "sv": { "name" : "Havsområden"},"en": { "name" : "Sea regions"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Biomaantieteelliset alueet"}, "sv": { "name" : "Biogeografiska regioner"},"en": { "name" : "Bio-geographical regions"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Elinympäristöt ja biotoopit"}, "sv": { "name" : "Naturtyper och biotoper"},"en": { "name" : "Habitats and biotopes"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Lajien levinneisyys"}, "sv": { "name" : "Arters utbredning"},"en": { "name" : "Species distribution"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Energiavarat"}, "sv": { "name" : "Energiresurser"},"en": { "name" : "Energy resources"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Mineraalivarat"}, "sv": { "name" : "Mineralfyndigheter"},"en": { "name" : "Mineral resources"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Taustakartat"}, "sv": { "name" : "Bakgrundskartor"},"en": { "name" : "Background maps"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Muut"}, "sv": { "name" : "Andra"},"en": { "name" : "Others"}}');
INSERT INTO portti_inspiretheme (locale) values ('{"fi":{"name":"Opaskartat"}, "sv": { "name" : "Guidekartor"},"en": { "name" : "Guide maps"}}');


-- Add tutorial layers here;
