ALTER TABLE categories
DROP COLUMN IF EXISTS stroke_width CASCADE,
DROP COLUMN IF EXISTS stroke_color CASCADE,
DROP COLUMN IF EXISTS fill_color CASCADE,
DROP COLUMN IF EXISTS dot_color CASCADE,
DROP COLUMN IF EXISTS dot_size CASCADE,
DROP COLUMN IF EXISTS border_width CASCADE,
DROP COLUMN IF EXISTS border_color CASCADE,
DROP COLUMN IF EXISTS dot_shape CASCADE,
DROP COLUMN IF EXISTS stroke_linejoin CASCADE,
DROP COLUMN IF EXISTS fill_pattern CASCADE,
DROP COLUMN IF EXISTS stroke_linecap CASCADE,
DROP COLUMN IF EXISTS stroke_dasharray CASCADE,
DROP COLUMN IF EXISTS border_linejoin CASCADE,
DROP COLUMN IF EXISTS border_dasharray CASCADE;

DROP TRIGGER IF EXISTS trigger_categories_update ON categories;
DROP FUNCTION procedure_categories_update()